sudo: false
branches:
  only:
  - develop
language: node_js
node_js:
- '7'
env:
  global:
  - SAUCE_USERNAME=readium
  - SAUCE_ACCESS_KEY=a36ebc10-e514-4da6-924c-307aec513550
  matrix:
  - MODE=chrome
  - MODE=firefox
#before_install:
#- npm install -g grunt-cli
install:
- yarn run prepare:yarn:all
script:
- npm run build
- npm run test:travis
